name: update-pull-request

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, edited, ready_for_review]
  
jobs:
  update-pull-request:
    uses: octue/workflows/.github/workflows/generate-pull-request-description.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
